name: flutter_movies
description: Projeto exemplo para listagem de filmes.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter

  get_it: ^7.6.4
  result_dart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.3
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
